### PR TITLE
[RFC] match naming cgrp with upstream Linux

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
This patchset renames the local variable `cgroup` -> `cgrp` to match
upstream Linux Kernel, across the files (most of the occurrence)
bringing it closer to the Linux kernel cgroup code.

### CODE REVIEW

**Comment by fmoessbauer** [comment]
This is only an internal change, right? Then I like it as it resolves the ambiguity between the parameter types and values.

**Comment by kamalesh-babulal** [comment]
@fmoessbauer Thanks for looking through it. Yes, the renaming is limited to internal code.

**Comment by kamalesh-babulal** [comment]
**V2 Changes**:
- Rebased to the current `main` branch

**Comment by drakenclimber** [comment]
Pushed to main.  Thanks for your patience, @kamalesh-babulal

**Comment by kamalesh-babulal** [comment]
@drakenclimber Thank you so much for reviewing and merging it.

**Pull request closed without merging**
