### PR TITLE
Introduce coding style in remaining source files

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
This patch series is the second of the series, that introduces coding style
cleanups.  It attempts to bring remaining source files under:
`src/*.[ch]`, `include/*`,  `dist/*`, `doc/*`, and other files
up to the coding style recommended by Linux Kernel's /scripts/checkpatch.pl.

Along with following the coding styles recommendation introduced in #106, it
adds another ignore type `.checkpatch.conf`:
`--ignore NEW_TYPEDEFS` – Complains about the declaration of new typedefs.

We have a couple of new typedefs declared in some source files, and they are
being caught by the `checkpatch.pl`, fixing those might need some refactoring. 
For now, let's ignore it and take it up later.

### CODE REVIEW

**Review by drakenclimber — APPROVED** [review]

**Comment by drakenclimber** [comment]
Man, that was a slog :).  This looks good to me, @kamalesh-babulal.  Thanks so much for all the hard work!!

Could you please rebase it on top of the latest main?

**Comment by kamalesh-babulal** [comment]
> Man, that was a slog :). This looks good to me, @kamalesh-babulal. Thanks so much for all the hard work!!

Thanks for the review @drakenclimber :)

**Comment by kamalesh-babulal** [comment]
**V2 Changes**
- Resolve the conflicts and rebase it on top of updated `main` branch.

**Comment by drakenclimber** [comment]
Thanks, @kamalesh-babulal.  Merged into main.

**Pull request closed without merging**
