### PR TITLE
Fix issue 133 `with_bindings = false`

### PR DESCRIPTION
**Pull request by jeffmacdonald**
https://github.com/libcgroup/libcgroup/issues/133

### CODE REVIEW

**Comment by kamalesh-babulal** [comment]
@jeffmacdonald Thanks for the patch. It looks good to me. Can you add your `Signed-off-by:` to the patch.

**Comment by drakenclimber** [comment]
https://github.com/libcgroup/libcgroup/blob/main/CONTRIBUTING.md#sign-your-work

**Comment by giani** [comment]
please also explain what/why was done in the commit log instead of just a link to a github issue. (but yes please retain the link to the issue if there is a lot more relevant information there)

**Comment by drakenclimber** [comment]
Thanks, @kamalesh-babulal and @jeffmacdonald.  Pushed to `release-2.0` in commit 4c4ada850f0e55314609f2f324c545cf7ea19a4c

**Pull request closed without merging**
